fixtures:
  repositories:
    stdlib:        "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    extlib:        "git://github.com/puppet-community/puppet-extlib.git"
    apache:        "git://github.com/puppetlabs/puppetlabs-apache.git"
    vcsrepo:       "git://github.com/puppetlabs/puppetlabs-vcsrepo.git"
    postgresql:    "git://github.com/puppetlabs/puppetlabs-postgresql.git"
    mongodb:       "git://github.com/puppetlabs/puppetlabs-mongodb.git"
    concat:        "git://github.com/puppetlabs/puppetlabs-concat.git"
    certs:         "git://github.com/katello/puppet-certs.git"
    katello:       "git://github.com/katello/puppet-katello.git"
    common:        "git://github.com/katello/puppet-common.git"
    candlepin:     "git://github.com/katello/puppet-candlepin.git"
    pulp:          "git://github.com/katello/puppet-pulp.git"
    crane:         "git://github.com/katello/puppet-crane.git"
    qpid:          "git://github.com/katello/puppet-qpid.git"
    elasticsearch: "git://github.com/katello/puppet-elasticsearch.git"
    foreman:       "git://github.com/theforeman/puppet-foreman.git"
  symlinks:
    katello_devel: "#{source_dir}"
